### PR TITLE
Add another way to generate *.cabal from *.dhall.

### PR DESCRIPTION
**Pull request by philderbeast**
You can see an example of it in use at https://github.com/BlockScope/flare-timing/blob/master/lang-haskell/flare-timing/package.dhall.

### CODE REVIEW

**Comment by philderbeast** [comment]
@vrom911 I've tried a lot of ways of building Haskell packages and projects. Not all of my experiments have I maintained but their once living corpses (hopefully harmless stray files) are littered through a large project I used to test these on. I'd clean these out but I feel like I want to go back and revive them all and write a blog post about the myriad possible ways of building Haskell. Maybe you saw some `package.yaml` files there alongside the `package.dhall` files?

I took over ownership of hpack-dhall and use`dhall-hpack-cabal` in my everyday workflow. I find it any easy way to keep `*.cabal` files up to date. This exe does not write `*.yaml` files, only `*.cabal` ones.

**Comment by philderbeast** [comment]
The section I would like `dhall-hpack-cabal` added to is

> Cabal integration with other configuration languages and formats.

Two of the exes in that list already depend on hpack but these do not have hpack in their names, `cabal2nix` and `stack2cabal`.

https://packdeps.haskellers.com/reverse/hpack

Perhaps in the future cabal2nix will drop this dependency on hpack.

https://github.com/NixOS/cabal2nix/pull/375#issuecomment-431089214

The `stack2cabal` exe will convert `package.yaml` to `*.cabal`.

**Comment by vrom911** [comment]
Thank you for your thoughtful reply. I see how you care about the tool, I appreciate that!

I've noticed that the specifications used in the `dhall-hpack-cabal` format are based on the `hpack` fields specification (at least this is what I see in the files and docs). This gives a feeling that you want to pinpoint that this tool is based on Hpack and takes the hard usage of it, as you force this in the description you provided in the PR. 
Each of `dhall-to-cabal`, `cabal2nix` and `stack2cabal` provide integrations with the whole ecosystem. Unlike `hpack`, they are not inventing new syntax and are trying to be in harmony with the cabal format in terms of the semantics. On the other hand, `hpack` provides an alternative syntax for defining `.cabal` files, which I referred to as "confusing" for beginners who are trying to learn plain cabal or looking for the ways how to integrate it with other systems. We are willing to keep this list more lucid, that's why hard advertisement of the tools that could confuse people in here is not something that we are considering to do that easily. Sorry, if my understanding of your intentions is not correct...

**Comment by chshersh** [comment]
Closing this as `wontfix`. I believe the discussions sums up our reasoning quite accurately. Nevertheless, @philderbeast thanks for your effort! It's always nice to know about different projects in the Haskell ecosystem :slightly_smiling_face: But, unfortunately, `dhall-hpack-cabal` is out of the scope for `awesome-cabal`.

**Pull request closed without merging**
